### PR TITLE
Fix nulls in aggregations with distinct

### LINKED ISSUE #6395: SQL: panic: float encoding is neither 4 nor 8 bytes
## tl;dr

```
$ super -version
Version: 9db7691f8

$ super -c "SELECT SUM(DISTINCT CAST(NULL AS REAL));"
panic: float encoding is neither 4 nor 8 bytes

goroutine 50 [running]:
github.com/brimdata/super.DecodeFloat({0xc0004cd139?, 0xc00011fa68?, 0xc0004cd129?})
	/Users/phil/work/super/primitive.go:100 +0x86
github.com/brimdata/super.Value.Float({{0x7ebb9a0?, 0x9073900?}, 0xc0004cd139?, 0x5ed2425?})
	/Users/phil/work/super/value.go:142 +0x78
github.com/brimdata/super/runtime/sam/expr/coerce.ToFloat({{0x7ebb9a0?, 0x9073900?}, 0xc0004cd139?, 0x0?}, {0x7ebb9c8, 0x9073900})
	/Users/phil/work/super/runtime/sam/expr/coerce/cast.go:77 +0x14a
github.com/brimdata/super/runtime/sam/expr/agg.(*Float64).consume(0xc00019d390, {{0x7ebb9a0?, 0x9073900?}, 0xc0004cd139?, 0x8?})
	/Users/phil/work/super/runtime/sam/expr/agg/math.go:143 +0x45
github.com/brimdata/super/runtime/sam/expr/agg.(*mathReducer).consumeVal(0xc00002fbc0, {{0x7ebb9a0?, 0x9073900?}, 0xc0004cd139?, 0x0?})
	/Users/phil/work/super/runtime/sam/expr/agg/math.go:90 +0x36c
github.com/brimdata/super/runtime/sam/expr/agg.(*mathReducer).Consume(0xc0004cd138?, {{0x7ebb9a0?, 0x9073900?}, 0xc0004cd139?, 0xc00011fc80?})
	/Users/phil/work/super/runtime/sam/expr/agg/math.go:46 +0x25
github.com/brimdata/super/runtime/sam/expr/agg.(*distinct).Result(0xc0001e6dc0, 0xc000357cb0)
	/Users/phil/work/super/runtime/sam/expr/agg/distinct.go:63 +0x10b
github.com/brimdata/super/runtime/sam/op/aggregate.(*Aggregator).readTable(0xc000030900, 0x1, 0x0, {0x9073900?, 0x0?})
	/Users/phil/work/super/runtime/sam/op/aggregate/aggregate.go:549 +0x7a3
github.com/brimdata/super/runtime/sam/op/aggregate.(*Aggregator).nextResult(0xc000030900?, 0xb0?, {0x7ec6ab0?, 0xc0006a1f40?})
	/Users/phil/work/super/runtime/sam/op/aggregate/aggregate.go:411 +0x8f
github.com/brimdata/super/runtime/sam/op/aggregate.(*Op).run.func2(...)
	/Users/phil/work/super/runtime/sam/op/aggregate/aggregate.go:181
github.com/brimdata/super/runtime/sam/op/aggregate.(*Op).run(0xc0001e6d20)
	/Users/phil/work/super/runtime/sam/op/aggregate/aggregate.go:203 +0x19b
created by github.com/brimdata/super/runtime/sam/op/aggregate.(*Op).Pull.func1 in goroutine 1
	/Users/phil/work/super/runtime/sam/op/aggregate/aggregate.go:163 +0x66
```

## Details

Repro is with super commit 9db7691.

This query is a simplification of a query from [a sqllogictest](https://github.com/dolthub/sqllogictest/blob/a1f4aa3c1d691552a4a03d9603c45bcf93d0bb9d/test/random/aggregates/slt_good_10.test#L51524-L51528) that first uncovered the issue.

Here's Postgres returning the expected result:

```
$ psql --versio
psql (PostgreSQL) 17.7 (Homebrew)

$ psql postgres -c '\pset null NULL' -c "SELECT SUM(DISTINCT CAST(NULL AS REAL));"
Null display is "NULL".
 sum  
------
 NULL
(1 row)
```

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #6395

### CODE REVIEW

**Comment by philrz** [comment]
This branch tests out nicely for me! 👍

File: runtime/vam/expr/agg/distinct.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ func (d *distinct) Consume(vec vector.Any) {
 		b.Truncate()
 		vec.Serialize(&b, i)
 		d.buf = binary.AppendVarint(d.buf[:0], int64(id))
-		d.buf = append(d.buf, b.Bytes().Body()...)
+		d.buf = scode.Append(d.buf, b.Bytes().Body())
```
Comment (nwt) [inline runtime/vam/expr/agg/distinct.go]: scode.Append adds the same bytes removed by scode.Bytes.Body.

```suggestion
		d.buf = append(d.buf, b.Bytes()...)
```
