### PR TITLE
fix SQL badSchema ref bug and path clone bug in schema star

### LINKED ISSUE #6527: SQL: Panic when attempting JOIN query on absent inputs
Repro is with super commit 292f441.

I happened to accidentally run a query while in an empty directory where the referenced inputs were not present. Instead of an error message I got a panic.

```
$ super -version
Version: 292f4415e

$ super -c "SELECT * FROM tab1 LEFT OUTER JOIN tab2 ON true;"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7d32233]

goroutine 1 [running]:
github.com/brimdata/super/compiler/semantic.(*staticTable).star(0xc0007a0f70?, {0x8611358, 0xc0004134d0}, {0x0?, 0x829cdc0?}, {0xc0007911c0, 0x2, 0x2})
	/Users/phil/work/super/compiler/semantic/schema.go:406 +0xb3
github.com/brimdata/super/compiler/semantic.(*joinScope).star(0xc000791160, {0x8611358, 0xc0004134d0}, {0x0, 0x0}, {0xc0007a0f70, 0x6603945?, 0x1})
	/Users/phil/work/super/compiler/semantic/schema.go:350 +0x10d
github.com/brimdata/super/compiler/semantic.(*selectScope).star(...)
	/Users/phil/work/super/compiler/semantic/schema.go:400
github.com/brimdata/super/compiler/semantic.(*translator).formProjection(0xc00041b5e0, 0xc0007a2c80, {0xc00043e280, 0x1, 0x1?})
	/Users/phil/work/super/compiler/semantic/sql.go:137 +0x3b3
github.com/brimdata/super/compiler/semantic.(*translator).sqlSelect(0xc00041b5e0, 0xc00012a640, {0x0, 0x0, 0x0?}, {0x0?, 0x0?, 0x0?})
	/Users/phil/work/super/compiler/semantic/sql.go:54 +0x2a5
github.com/brimdata/super/compiler/semantic.(*translator).sqlQueryBody(0xc0001bc5a0?, {0x861a710?, 0xc00012a640?}, {0x0?, 0x0?, 0x0?}, {0x0?, 0x0?, 0xc000369e60?})
	/Users/phil/work/super/compiler/semantic/sql.go:416 +0x2a5
github.com/brimdata/super/compiler/semantic.(*translator).sqlQueryBody(0xc00041b5e0, {0x861a290?, 0xc00038d4a0}, {0x0?, 0x1?, 0x0?}, {0x0, 0x0, 0x0})
	/Users/phil/work/super/compiler/semantic/sql.go:428 +0xf25
github.com/brimdata/super/compiler/semantic.(*translator).semOp(0xc00041b5e0, {0x861ad10?, 0xc00003fec0}, {0x0, 0x0, 0x0})
	/Users/phil/work/super/compiler/semantic/op.go:543 +0x6d5
github.com/brimdata/super/compiler/semantic.(*translator).seq(...)
	/Users/phil/work/super/compiler/semantic/op.go:32
github.com/brimdata/super/compiler/semantic.Analyze({0x8623080?, 0xc0001bc750?}, 0xc0007910c0, 0x6652b25?, 0x0)
	/Users/phil/work/super/compiler/semantic/analyzer.go:26 +0x1d0
github.com/brimdata/super/compiler.Analyze(...)
	/Users/phil/work/super/compiler/package.go:24
github.com/brimdata/super/compiler.CompileWithAST(0xc0001bc750, 0x6781c45?, 0xc00041b570, 0x1, 0xc, {0x0, 0x0, 0x0})
	/Users/phil/work/super/compiler/package.go:65 +0x65
github.com/brimdata/super/compiler.(*compiler).NewQuery(0x8623128?, 0xc000128320?, 0xc0004699f0?, {0x0?, 0x90?, 0x859d520?}, 0x66ae500?)
	/Users/phil/work/super/compiler/compiler.go:42 +0x45
github.com/brimdata/super/runtime.CompileQuery({0x8623128?, 0xc000128320?}, 0xc00042c2d0, {0x860fcc0, 0xc00042a080}, 0xc0007910c0, {0x0, 0x0, 0x0})
	/Users/phil/work/super/runtime/compiler.go:34 +0x10f
github.com/brimdata/super/cmd/super/root.(*Command).Run(0xc000422488, {0xc00003e8f0, 0x0, 0x0})
	/Users/phil/work/super/cmd/super/root/command.go:152 +0x54b
github.com/brimdata/super/pkg/charm.path.run({0xc000114088, 0x1, 0x1}, {0xc00003e8f0, 0x0, 0x0?})
	/Users/phil/work/super/pkg/charm/path.go:11 +0x7b
github.com/brimdata/super/pkg/charm.(*Spec).Exec(0x97b6f00, {0xc00003e8e0, 0x2, 0x2})
	/Users/phil/work/super/pkg/charm/charm.go:74 +0x1fa
main.main()
	/Users/phil/work/super/cmd/super/main.go:39 +0x5b
```

### LINKED ISSUE #6537: SQL: Incorrect columns returned and panic in cross join variations
These three problems surfaced while studying a failed sqllogictest.

```
$ super -version
Version: 6205ec1a0

$ super -f tsv -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)) t2 CROSS JOIN (VALUES (5,6)) t3;"
c0	c1	c1_1	c1_2	c1_3	c1_4
1	2	4	4	6	6

$ super -f tsv -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)) t2, (VALUES (5,6)) t3;"
c1	c1_1	c1_2	c1_3	c0	c1_4
2	2	4	4	5	6

$ super -f tsv -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)), t2, (VALUES (5,6)) t3;"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x101a3ebac]

goroutine 1 [running]:
github.com/brimdata/super/compiler/semantic.(*staticTable).star(0x140002c11e0?, {0x1022c5a78, 0x1400049c900}, {0x0?, 0x101f52900?}, {0x140003388c0, 0x3, 0x4})
	/Users/runner/super/compiler/semantic/schema.go:406 +0x8c
github.com/brimdata/super/compiler/semantic.(*joinScope).star(0x140002c0b40, {0x1022c5a78, 0x1400049c900}, {0x0, 0x0}, {0x140002c11e0, 0x1400051e508?, 0x2})
	/Users/runner/super/compiler/semantic/schema.go:354 +0x1a8
github.com/brimdata/super/compiler/semantic.(*joinScope).star(0x140002c11a0, {0x1022c5a78, 0x1400049c900}, {0x0, 0x0}, {0x140001e7500, 0x10338fc20?, 0x1})
	/Users/runner/super/compiler/semantic/schema.go:350 +0xe8
github.com/brimdata/super/compiler/semantic.(*selectScope).star(...)
	/Users/runner/super/compiler/semantic/schema.go:400
github.com/brimdata/super/compiler/semantic.(*translator).formProjection(0x1400041bdc0, 0x1400009a800, {0x140003a7740, 0x1, 0x4?})
	/Users/runner/super/compiler/semantic/sql.go:137 +0x2bc
github.com/brimdata/super/compiler/semantic.(*translator).sqlSelect(0x1400041bdc0, 0x140003c3220, {0x0, 0x0, 0x0?}, {0x0?, 0x0?, 0x0?})
	/Users/runner/super/compiler/semantic/sql.go:54 +0x1f0
github.com/brimdata/super/compiler/semantic.(*translator).sqlQueryBody(0x1022a73e8?, {0x1022cee30?, 0x140003c3220?}, {0x0?, 0x0?, 0x1400036f1e8?}, {0x0?, 0x1?, 0x0?})
	/Users/runner/super/compiler/semantic/sql.go:416 +0x1f8
github.com/brimdata/super/compiler/semantic.(*translator).sqlQueryBody(0x1400041bdc0, {0x1022ce9b0?, 0x1400003d400}, {0x0?, 0x0?, 0x0?}, {0x0, 0x0, 0x0})
	/Users/runner/super/compiler/semantic/sql.go:428 +0xbb0
github.com/brimdata/super/compiler/semantic.(*translator).semOp(0x1400041bdc0, {0x1022cf430?, 0x140004a8150}, {0x0, 0x0, 0x0})
	/Users/runner/super/compiler/semantic/op.go:542 +0x554
github.com/brimdata/super/compiler/semantic.(*translator).seq(...)
	/Users/runner/super/compiler/semantic/op.go:32
github.com/brimdata/super/compiler/semantic.Analyze({0x1022d77a0?, 0x140004a8a20?}, 0x140000b5ee0, 0x1007c4b6c?, 0x0)
	/Users/runner/super/compiler/semantic/analyzer.go:26 +0x170
github.com/brimdata/super/compiler.Analyze(...)
	/Users/runner/super/compiler/package.go:24
github.com/brimdata/super/compiler.CompileWithAST(0x140004a8a20, 0x10168b974?, 0x1400041bd50, 0x1, 0x3, {0x0, 0x0, 0x0})
	/Users/runner/super/compiler/package.go:65 +0x54
github.com/brimdata/super/compiler.(*compiler).NewQuery(0x1022d7848?, 0x1400038f220?, 0x1400051f9d8?, {0x0?, 0x90?, 0x102252120?}, 0x0?)
	/Users/runner/super/compiler/compiler.go:42 +0x54
github.com/brimdata/super/runtime.CompileQuery({0x1022d7848?, 0x1400038f220?}, 0x1400042c3f0, {0x1022c43e0, 0x1400042a050}, 0x140000b5ee0, {0x0, 0x0, 0x0})
	/Users/runner/super/runtime/compiler.go:34 +0xcc
github.com/brimdata/super/cmd/super/root.(*Command).Run(0x140003866c8, {0x14000152040, 0x0, 0x0})
	/Users/runner/super/cmd/super/root/command.go:152 +0x414
github.com/brimdata/super/pkg/charm.path.run({0x1400012aa60, 0x1, 0x1}, {0x14000152040, 0x0, 0x0?})
	/Users/runner/super/pkg/charm/path.go:11 +0x60
github.com/brimdata/super/pkg/charm.(*Spec).Exec(0x10334bf60, {0x14000152010, 0x4, 0x4})
	/Users/runner/super/pkg/charm/charm.go:74 +0x170
main.main()
	/Users/runner/super/cmd/super/main.go:39 +0x58
```

## Details

Repro is with super commit 6205ec1. The original sqllogictest that produced an incorrect result that inspired these simplified repros is [random/select/slt_good_9/q8108](https://github.com/brimdata/sqllogic-ztests/blob/main/ztests/sqlite/random/select/slt_good_9/ztests-1/q8108.fail).

Here's the expected results with Postgres.

```
$ psql postgres -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)) t2 CROSS JOIN (VALUES (5,6)) t3;"
 column1 | column2 | column1 | column2 | column1 | column2 
---------+---------+---------+---------+---------+---------
       1 |       2 |       3 |       4 |       5 |       6
(1 row)

$ psql postgres -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)) t2, (VALUES (5,6)) t3;"
 column1 | column2 | column1 | column2 | column1 | column2 
---------+---------+---------+---------+---------+---------
       1 |       2 |       3 |       4 |       5 |       6
(1 row)

$ psql postgres -c "SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)), t2, (VALUES (5,6)) t3;"
ERROR:  relation "t2" does not exist
LINE 1: SELECT * FROM (VALUES (1,2)) t1, (VALUES (3,4)), t2, (VALUES...
                                                         ^
```

As you can see, that final one was effectively a typo I made while crafting the middle query, so it's not like I expected it to work with `super`. I just always react to panics.

### PR DESCRIPTION
**Pull request by mccanne**
Fixes #6537
Fixes #6527

### CODE REVIEW

File: compiler/semantic/analyzer.go [hunk 1]
```diff
@@ -71,6 +71,7 @@ func newTranslator(ctx context.Context, r reporter, env *exec.Environment) *tran
 		scope:    NewScope(nil),
 		sctx:     super.NewContext(),
 	}
+	badTable.typ = t.sctx.MustLookupTypeRecord([]super.Field{})
```
Comment (nwt) [inline compiler/semantic/analyzer.go]: Storing a type from t.sctx in a package-level variable is dubious. How about this instead?

```diff
diff --git a/compiler/semantic/schema.go b/compiler/semantic/schema.go
index 327a912df..acae88c9f 100644
--- a/compiler/semantic/schema.go
+++ b/compiler/semantic/schema.go
@@ -401,6 +401,9 @@ func (s *selectScope) star(n ast.Node, table string, path field.Path) ([]*sem.Th
 }

 func (s *staticTable) star(n ast.Node, table string, path field.Path) ([]*sem.ThisExpr, error) {
+       if s == badTable {
+               return nil, nil
+       }
        var out []*sem.ThisExpr
        if table == "" || s.table == table {
                for _, col := range s.typ.Fields {
```
