### PR TITLE
service/search: ignore request span if pool has no span

### LINKED ISSUE #2740: Can't post/get NDJSON with string key called "ts" (regression at dcce5c22)
Repro is with Zed commit dcce5c2 which is associated with #2729 (cc: @mccanne).

At Zed commit 7c92f41 that came right before, the following was working. First I start a `zed lake serve`:

```
$ zed -version
Version: v0.29.0-340-g7c92f41f

$ zed lake serve
{"level":"info","ts":1621453519.363533,"msg":"Open files limit raised","limit":24576}
{"level":"info","ts":1621453519.365165,"logger":"core","msg":"Started"}
{"level":"info","ts":1621453519.365385,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
```

Then I create a Pool and post sample data [https://github.com/brimdata/brim/blob/main/itest/testdata/sample.ndjson](https://github.com/brimdata/brim/blob/main/itest/testdata/sample.ndjson) to it.

```
$ zapi new foo
foo: pool created

$ zapi post -p foo sample.ndjson
posted 13.01KB in 6.883174ms

$ zapi get -p foo -z
{_path:"capture_loss",_write_ts:"2020-02-25T16:03:17.838527Z",ts:"2020-02-25T16:03:17.838527Z",ts_delta:11.854892015457153,peer:"zeek",gaps:0,acks:6,percent_lost:0.}
...
```

However, advancing to Zed commit dcce5c2, now the `get` returns nothing.

```
$ zed -version
Version: v0.29.0-341-gdcce5c22

$ zed lake serve
{"level":"info","ts":1621453687.019802,"msg":"Open files limit raised","limit":24576}
{"level":"info","ts":1621453687.021408,"logger":"core","msg":"Started"}
{"level":"info","ts":1621453687.021627,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
```

```
$ zapi new foo
foo: pool created

$ zapi post -p foo sample.ndjson
posted 13.01KB in 7.48606ms

$ zapi get -p foo -z
[no output]

$ echo $?
0
```

Back in the `zed lake serve` window, I see no crash or other indications of a problem.

```
...
{"level":"info","ts":1621453709.27301,"logger":"http.access","msg":"Request completed","request_id":"1slijHS76xjG8e2Vw60KPdScLZq","host":"localhost:9867","method":"POST","proto":"HTTP/1.1","remote_addr":"[::1]:54870","request_content_length":64,"url":"/pool","elapsed":0.001180324,"response_content_length":50,"status_code":200}
{"level":"info","ts":1621453713.043034,"logger":"http.access","msg":"Request completed","request_id":"1slijhFYrx5qoM3CQolHHf0xqqn","host":"localhost:9867","method":"GET","proto":"HTTP/1.1","remote_addr":"[::1]:54874","request_content_length":0,"url":"/pool","elapsed":0.000018305,"response_content_length":52,"status_code":200}
{"level":"info","ts":1621453713.044298,"logger":"http.access","msg":"Request completed","request_id":"1slijlyVCC2bVU2Y17dhklzska5","host":"localhost:9867","method":"GET","proto":"HTTP/1.1","remote_addr":"[::1]:54875","request_content_length":0,"url":"/pool","elapsed":0.000009788,"response_content_length":52,"status_code":200}
{"level":"info","ts":1621453713.052016,"logger":"http.access","msg":"Request completed","request_id":"1slijinDTY0EHWuNyeUwZX4iSRP","host":"localhost:9867","method":"POST","proto":"HTTP/1.1","remote_addr":"[::1]:54875","request_content_length":-1,"url":"/pool/1slijAiDMSPfSrirOCjVo0mwP1A/log","elapsed":0.007054416,"response_content_length":101,"status_code":200}
{"level":"info","ts":1621453717.537225,"logger":"http.access","msg":"Request completed","request_id":"1slikBaW6Tw1dpmG7d2TMNpxWmT","host":"localhost:9867","method":"GET","proto":"HTTP/1.1","remote_addr":"[::1]:54880","request_content_length":0,"url":"/pool","elapsed":0.000011747,"response_content_length":52,"status_code":200}
{"level":"info","ts":1621453717.541022,"logger":"http.access","msg":"Request completed","request_id":"1slikEexnyHsXv6Ch4ikvQaDRHM","host":"localhost:9867","method":"POST","proto":"HTTP/1.1","remote_addr":"[::1]:54880","request_content_length":246,"url":"/search?format=zng","elapsed":0.002319086,"response_content_length":312,"status_code":200}
```

### PR DESCRIPTION
**Pull request by nwt**
Closes #2740.

### CODE REVIEW

**Review by mccanne — APPROVED** [review]

File: service/search/search.go [hunk 1]
```diff
@@ -132,6 +132,18 @@ func (s *SearchOp) Run(ctx context.Context, adaptor proc.DataAdaptor, pool *lake
 	return driver.RunWithLakeAndStats(ctx, d, seq, zctx, adaptor, statsTicker.C, s.logger, parallelism)
 }
 
+func poolHasSpan(ctx context.Context, pool *lake.Pool) bool {
```
Comment (mccanne) [inline service/search/search.go:135]: I think this can just check len(pool.Layout.Keys) == 0

Comment (nwt) [reply service/search/search.go:135]: That'll break the app in a different way since it currently creates pools with no key.
