### PR TITLE
agg distinct: Fix view generation in ConsumeAsPartial

### LINKED ISSUE #6785: SQL: Incorrect/inconsistent aggregation on JSON in vector runtime
The aggregation query result below is incorrect in vector runtime and changes on repeated runs. It should have produced `users:50464` for the last field in the record.

```
$ curl -s -O https://clickhouse-public-datasets.s3.amazonaws.com/bluesky/file_0001.json.gz &&
  super -version &&
  super -vam -s -c "
SELECT
    commit.collection AS event,
    count() AS count,
    count(distinct did) AS users
FROM 'file_0001.json.gz'
WHERE kind = 'commit'
  AND commit.operation = 'create'
GROUP BY event
ORDER BY count DESC;
  " | grep '"app.bsky.feed.post"'

Version: v0.3.0-22-gea538e8ec
{event:"app.bsky.feed.post",count:86812,users:113065}
```

```
$ super -vam -s -c "
SELECT
    commit.collection AS event,
    count() AS count,
    count(distinct did) AS users
FROM 'file_0001.json.gz'
WHERE kind = 'commit'
  AND commit.operation = 'create'
GROUP BY event
ORDER BY count DESC;
  " | grep '"app.bsky.feed.post"'

{event:"app.bsky.feed.post",count:86812,users:113485}
```

## Details

Repro is with super commit ea538e8. The query is the SuperSQL equivalent of the [q2 query](https://github.com/ClickHouse/JSONBench/blob/e6c7c98dc766394d51f7d506a3dd2b5d51165d70/clickhouse/queries.sql#L2) from [JSONBench](https://jsonbench.com/).

The expected result is produced consistently if the query against JSON is run in sequential runtime.

```
$ super -sam -s -c "
SELECT
    commit.collection AS event,
    count() AS count,
    count(distinct did) AS users
FROM 'file_0001.json.gz'
WHERE kind = 'commit'
  AND commit.operation = 'create'
GROUP BY event
ORDER BY count DESC;
  " | grep '"app.bsky.feed.post"'

{event:"app.bsky.feed.post",count:86812,users:50464}
```

A binary search revealed that this bug first appeared when the changes merged from #6514. This was in the days that `SUPER_VAM` was needed to force running in vector runtime.

```
$ super -version && SUPER_VAM=1 super -s -c "
SELECT
    commit.collection AS event,
    count() AS count,
    count(distinct did) AS users
FROM 'file_0001.json.gz'
WHERE kind = 'commit'
  AND commit.operation = 'create'
GROUP BY event
ORDER BY count DESC;
  " | grep '"app.bsky.feed.post"'

Version: 03130efdf
{event:"app.bsky.feed.post",count:86812,users:113217}
```

If I go back one commit before the changes from #6514 merged, we get the expected result in vector runtime.

```
$ super -version && SUPER_VAM=1 super -s -c "
SELECT
    commit.collection AS event,
    count() AS count,
    count(distinct did) AS users
FROM 'file_0001.json.gz'
WHERE kind = 'commit'
  AND commit.operation = 'create'
GROUP BY event
ORDER BY count DESC;
  " | grep '"app.bsky.feed.post"'

Version: 81a35340a
{event:"app.bsky.feed.post",count:86812,users:50464}
```

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #6785

### CODE REVIEW

File: runtime/vam/expr/agg/distinct.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func (d *distinct) ConsumeAsPartial(vec vector.Any) {
 	}
 	start, end := vector.ContainerOffset(array, slot)
 	values := array.Values
-	if start > 0 || end < vec.Len() {
+	if start > 0 || end < values.Len() {
```
Comment (nwt) [inline runtime/vam/expr/agg/distinct.go:52]: Sad.

Comment (mattnibs) [reply runtime/vam/expr/agg/distinct.go:52]: haha!
