### PR TITLE
vam: Fix null+null arithmetic

### LINKED ISSUE #6484: SQL: Vector runtime errors on arithmetic with CASE expression returning NULL
These all produce unexpected error values in vector runtime.

```
$ SUPER_VAM=1 super -c "SELECT CASE 1 WHEN 0 THEN 1 END + NULL;"
{"case 1 when 0 then 1 end+":error("type null incompatible with '+' operator")}

$ SUPER_VAM=1 super -c "SELECT CASE 1 WHEN 0 THEN 1 END * NULL;"
{"case 1 when 0 then 1 end*":error("type null incompatible with '*' operator")}

$ SUPER_VAM=1 super -c "SELECT CASE 1 WHEN 0 THEN 1 END / NULL;"
{"case 1 when 0 then 1 end/":error("type null incompatible with '/' operator")}
```

## Details

Repro is with super commit 5ea0cb5. The queries shown above are simplifications from sqllogictests that produce the same errors, such as [random/expr/slt_good_117/q1055](https://github.com/brimdata/sqllogic-ztests/blob/main/ztests/sqlite/random/expr/slt_good_117/ztests-1/q1055.yaml) (addition), [random/expr/slt_good_102/q2684](https://github.com/brimdata/sqllogic-ztests/blob/main/ztests/sqlite/random/expr/slt_good_102/ztests-1/q2684.yaml) (multiplication), and [random/expr/slt_good_105/q9770](https://github.com/brimdata/sqllogic-ztests/blob/main/ztests/sqlite/random/expr/slt_good_105/ztests-1/q9770.yaml) (division).

Here's the expected results being returned in sequential runtime and Postgres.

```
$ super -version
Version: 5ea0cb5d6

$ super -c "SELECT CASE 1 WHEN 0 THEN 1 END + NULL;"
{"case 1 when 0 then 1 end+":null}

$ super -c "SELECT CASE 1 WHEN 0 THEN 1 END * NULL;"
{"case 1 when 0 then 1 end*":null}

$ super -c "SELECT CASE 1 WHEN 0 THEN 1 END / NULL;"
{"case 1 when 0 then 1 end/":null}
```

```
$ psql postgres
psql (17.7 (Homebrew))
Type "help" for help.

postgres=# \pset null 'NULL'
Null display is "NULL".
postgres=# SELECT CASE 1 WHEN 0 THEN 1 END + NULL;
 ?column? 
----------
     NULL
(1 row)

postgres=# SELECT CASE 1 WHEN 0 THEN 1 END * NULL;
 ?column? 
----------
     NULL
(1 row)

postgres=# SELECT CASE 1 WHEN 0 THEN 1 END / NULL;
 ?column? 
----------
     NULL
(1 row)
```

### PR DESCRIPTION
**Pull request by mattnibs**
Fixes #6484

### CODE REVIEW

File: runtime/vam/expr/arith.go [hunk 1]
```diff
@@ -48,6 +48,9 @@ func (a *Arith) eval(vecs ...vector.Any) (out vector.Any) {
 	if kind == vector.KindFloat && a.opCode == vector.ArithMod {
 		return vector.NewStringError(a.sctx, "type float64 incompatible with '%' operator", lhs.Len())
 	}
+	if kind == vector.KindNull {
+		return vector.NewConst(super.Null, lhs.Len(), bitvec.NewTrue(lhs.Len()))
+	}
```
Comment (nwt) [inline runtime/vam/expr/arith.go]: Nit: Checking for KindNull earlier, when we check for KindError. That way we don't have to call vector.NewConst twice (once in coerceVals and then again here).

```go
	if k := vector.KindOf(lhs); k == vector.KindNull || k == vector.KindError {
		return lhs
	}
	if k := vector.KindOf(rhs); k == vector.KindNull || k == vector.KindError {
		return rhs
	}
```

**Review by nwt — APPROVED** [review]

File: runtime/vam/expr/arith.go (hunk 1 above)
Comment (mattnibs) [reply runtime/vam/expr/arith.go]: Nice!
