### PR TITLE
require "on" keyword for join and fix -C output

### LINKED ISSUE #2483: Incorrect canonical Zed for "join"
Here's some Zed I show off in the `join` cookbook:

```
$ cat join-uid-conn-fused.zed
split (
  => filter _path=conn | sort uid
  => filter _path=spl | sort uid
) | left join uid=uid orig_spl,resp_spl,orig_spt,resp_spt | fuse
```

It runs fine in that form with `zq` commit dd946d3.

```
$ zq -z -I join-uid-conn-fused.zed conn.log spl.log 
{_path:"conn",ts:2020-09-01T20:48:11.39799Z,uid:"C09v4A1ThuoXr4Ucdc" (bstring),id:{orig_h:10.9.1.101,orig_p:49836 (port=(uint16)),resp_h:86.104.194.116,resp_p:443 (port)} (=0),proto:"tcp" (=zenum),service:null (bstring),duration:153.774ms,orig_bytes:0 (uint64),resp_bytes:0 (uint64),conn_state:"REJ" (bstring),local_orig:null (bool),local_resp:null (bool),missed_bytes:0 (uint64),history:"Sr" (bstring),orig_pkts:1 (uint64),orig_ip_bytes:52 (uint64),resp_pkts:1 (uint64),resp_ip_bytes:40 (uint64),tunnel_parents:null (1=(|[bstring]|)),orig_spl:null (2=([uint64])),resp_spl:null (2),orig_spt:null (3=([float64])),resp_spt:null (3)} (=4)
...
```

However, if I send the Zed on a round trip through the canonical Zed generator, it no longer parses.

```
$ zast -C $(cat join-uid-conn-fused.zed) | tee busted.zed
split (
  =>
    filter _path="conn"
    | sort uid
  =>
    filter _path="spl"
    | sort uid
)
| join on uid=uid
  join-cut orig_spl,resp_spl,orig_spt,resp_spt
| fuse

$ zq -z -I busted.zed conn.log spl.log 
zq: parse error: error parsing Z at line 9, col 11:split (
  =>
    filter _path="conn"
    | sort uid
  =>
    filter _path="spl"
    | sort uid
)
| join on uid=uid
      === ^ ===
  join-cut orig_spl,resp_spl,orig_spt,resp_spt
| fuse
```

### LINKED ISSUE #2498: Add SQL-style "on" keyword with "join"
[SQL-style joins](https://www.w3schools.com/sql/sql_join.asp) look something like:

> SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate  
> FROM Orders  
> INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;

In Zed, `join` currently doesn't require the `on` keyword, but when being a user of it in Zed, @mccanne has been confused by its absence, so we should add it since it'll surely be appreciated by SQL users as well.

### PR DESCRIPTION
**Pull request by mccanne**
Closes #2483
Closes #2498

### CODE REVIEW

File: zfmt/dag.go [hunk 1]
```diff
@@ -310,10 +310,10 @@ func (c *canonDAG) op(p dag.Op) {
...
 		c.write("=")
 		c.expr(p.RightKey, false)
-		c.ret()
-		c.open("join-cut ")
-		c.assignments(p.Args)
-		c.close()
+		if len(p.Args) != 0 {
+			c.write(" ")
+			c.assignments(p.Args)
+		}
```
Comment (nwt) [inline zfmt/dag.go:316]: Maybe add test coverage for this?

**Review by nwt — APPROVED** [review]
