### PR TITLE
better index format for multi-type multi-keys

### LINKED ISSUE #2923: create better index format for multi-typed multi-keys
The creation of field indexes currently fail when provided multiple keys (primary, secondary, etc).  Also, the primary key is currently renamed "key" presuming there is only one key.

We should change the microindex format to allow for multiple keys of varied types and clean this all up.

### PR DESCRIPTION
**Pull request by mattnibs**
For microindexes, store the key name(s) in the trailer (without type)
and do not rename the key to "key", rather keep the original record
name.

Allow a key to have multiple typed values.

Closes #2923

### CODE REVIEW

File: index/mem.go [hunk 1]
```diff
@@ -58,56 +48,26 @@ func (t *MemTable) open() {
...
+		for _, value := range t.table {
+			t.values = append(t.values, value)
 		}
-		compare := expr.LookupCompare(t.keyType)
-		sort.SliceStable(t.keys, func(a, b int) bool {
-			return compare(t.keys[a], t.keys[b]) < 0
+		resolvers := make([]expr.Evaluator, len(t.keys))
+		for k, key := range t.keys {
+			resolvers[k] = expr.NewDotExpr(key)
+		}
```
Comment (nwt) [inline index/mem.go:58]: Use `append` here for consistency with the handling of `t.values`.
```suggestion
		resolvers := make([]expr.Evaluator, 0, len(t.keys))
		for _, key := range t.keys {
			resolvers = append(resolvers, expr.NewDotExpr(key))
		}
```

File: index/mem.go [hunk 2]
```diff
@@ -58,56 +48,26 @@ func (t *MemTable) open() {
...
+		compare := expr.NewCompareFn(false, resolvers...)
+		sort.SliceStable(t.values, func(a, b int) bool {
+			return compare(t.values[a], t.values[b]) < 0
 		})
```
Comment (nwt) [inline index/mem.go:62]:
```suggestion
		expr.SortStable(t.values, expr.NewCompareFn(false, resolvers...))
```

File: index/trailer.go [hunk 3]
```diff
@@ -7,75 +7,42 @@ import (
...
-		zed.EncodeInt(VersionVal),
-		zed.EncodeBool(desc),
-		zed.EncodeString(childField),
-		zed.EncodeInt(int64(frameThresh)),
-		encodeSections(sections),
-		nil), nil
-}
+var (
+	ErrNotIndex        = errors.New("not a zed index")
+	ErrTrailerNotFound = errors.New("zed index trailer not found")
```
Comment (nwt) [inline index/trailer.go:35]:
```suggestion
	ErrNotIndex        = errors.New("not a Zed index")
	ErrTrailerNotFound = errors.New("Zed index trailer not found")
```

File: index/trailer.go [hunk 4]
```diff
@@ -87,122 +54,42 @@ func readTrailer(r io.ReaderAt, size int64) (*Trailer, int, error) {
...
-		if zv.Type != zed.TypeInt64 {
-			return nil, errors.New("section element is not an int64")
-		}
-		size, err := zed.DecodeInt(zv.Bytes)
-		if err != nil {
-			return nil, errors.New("int64 section element could not be decoded")
-		}
-		sizes = append(sizes, size)
+	if trailer.Version != Version {
+		return nil, 0, fmt.Errorf("zed index version %d found while expecting version %d", trailer.Version, Version)
```
Comment (nwt) [inline index/trailer.go:82]:
```suggestion
		return nil, 0, fmt.Errorf("Zed index version %d found while expecting version %d", trailer.Version, Version)
```

File: index/writer.go [hunk 5]
```diff
@@ -77,20 +78,22 @@ type indexWriter struct {
...
 
-func NewWriterWithContext(ctx context.Context, zctx *zed.Context, engine storage.Engine, path string, options ...Option) (*Writer, error) {
+func NewWriterWithContext(ctx context.Context, zctx *zed.Context, engine storage.Engine, path string, keys field.List, options ...Option) (*Writer, error) {
 	w := &Writer{
-		zctx:   zctx,
-		engine: engine,
+		zctx:       zctx,
+		childField: uniqChildField(keys),
+		engine:     engine,
+		keys:       keys,
```
Comment (nwt) [inline index/writer.go:90]: Nit: Follow field declaration order.
```suggestion
		keys:       keys,
		zctx:       zctx,
		engine:     engine,
		childField: uniqChildField(keys),
```

File: index/writer.go [hunk 6]
```diff
@@ -77,20 +78,22 @@ type indexWriter struct {
...
 	}
 	for _, opt := range options {
 		opt.apply(w)
 	}
-	if w.keyFields == nil {
-		w.keyFields = field.List{field.New("key")}
+	if len(keys) == 0 {
+		return nil, errors.New("must specify at least one key")
 	}
```
Comment (nwt) [inline index/writer.go:97]: Nit: Do this before creating `w`.

File: index/ztests/different-types.yaml [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+outputs:
+  - name: stderr
+    data: ""
+  - name: stdout
+    data: |
+      {a:127.0.0.1}
+      {a:1.4}
+      {a:1}
+      {a:"hello"}
+
```
Comment (nwt) [inline index/ztests/different-types.yaml:26]:
```suggestion
```

File: lake/index/rule.go [hunk 8]
```diff
@@ -96,24 +96,20 @@ func Equivalent(a, b Rule) bool {
...
 	}
-	return fmt.Sprintf("cut %s:=%s | count() by %s | sort %s", keyName, f.Fields[0], keyName, keyName)
+	return fmt.Sprintf("cut %s | count() by %s | sort %s", fields, fields, fields)
 }
 
 func (t *TypeRule) Zed() string {
-	// XXX See issue #2923 as this doesn't make sense.
-	return fmt.Sprintf("explode this by %s as %s | count() by %s | sort %s", t.Type, keyName, keyName, keyName)
+	// XXX See issue #3140 as this does not allow for multiple type keys
+	return fmt.Sprintf("explode this by %s as %s | count() by %s | sort %s", t.Type, "key", "key", "key")
```
Comment (nwt) [inline lake/index/rule.go:112]:
```suggestion
	return fmt.Sprintf("explode this by %s as key | count() by key | sort key", t.Type)
```

File: index/ztests/manual.yaml [hunk 9]
```diff
@@ -1,8 +1,8 @@
 script: |
   zed index create -o index.zng -k s babble.zson
   zq -z index.zng > index.zson
-  zq -o sorted.zng "count() by s | put key:=s | cut key | sort key" babble.zson
-  zed index convert -o manual.zng -k key sorted.zng
+  zq -o sorted.zng "count() by s | cut s | sort s" babble.zson
```
Comment (nwt) [inline index/ztests/manual.yaml:4]:
```suggestion
  zq -o sorted.zng "by s | sort s" babble.zson
```

**Review by nwt — APPROVED** [review]
