### PR TITLE
pool.Squash: clear squashed commits

### LINKED ISSUE #2784: Committed entries still shown in "zed lake status" after commit
Repro is with Zed commit fd273d1 and the [Zeek zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-default).

I begin by creating a lake+pool, staging a couple logs via separate `add` operations, and then committing them.

```
$ zed -version
Version: v0.29.0-366-gfd273d11

$ rm -rf $ZED_LAKE_ROOT

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: file:///Users/phil/logs

$ zed lake create -p logs -orderby ts:desc
pool created: logs

$ zed lake add -p logs snmp.log.gz
1tRvK0kTROYpzbDo1UhlpMtu6KD staged

$ zed lake add -p logs pe.log.gz
1tRvKcrC6IaW782uRLhFRvhEdng staged
```

As expected, at this point the commits are shown as being in staging but don't yet appear in the commit log.

```
$ zed lake status -p logs
staged 1tRvK0kTROYpzbDo1UhlpMtu6KD

    Add 1tRvK0tMlG2B0DFJfCMSwwBkhm5 2KiB950B bytes 65 records
       from time: (00 52 5a 1c 89 d7 3d 2a) to time: (60 35 95 90 57 d5 3d 2a)

staged 1tRvKcrC6IaW782uRLhFRvhEdng

    Add 1tRvKfheRh2QcGK2Z4h3ZJd3ZJ2 1KiB138B bytes 21 records
       from time: (d0 6f 03 ad 5c d7 3d 2a) to time: (40 f3 f4 c1 5a d5 3d 2a)

$ zed lake log -p logs
empty log
```

However, when I commit them, they appear in the log (expected) but are _not_ purged from the staging output (unexpected).

```
$ zed lake commit -p logs 1tRvK0kTROYpzbDo1UhlpMtu6KD 1tRvKcrC6IaW782uRLhFRvhEdng
1tRvzSl76ZmK9E80rRL8yHgdDdC committed

$ zed lake log -p logs
commit 1tRvzSl76ZmK9E80rRL8yHgdDdC
Author: phil@PhilMac.local
Date:   2021-06-03T18:29:38Z

    Add 1tRvK0tMlG2B0DFJfCMSwwBkhm5 2KiB950B bytes 65 records
       from time: (00 52 5a 1c 89 d7 3d 2a) to time: (60 35 95 90 57 d5 3d 2a)
    Add 1tRvKfheRh2QcGK2Z4h3ZJd3ZJ2 1KiB138B bytes 21 records
       from time: (d0 6f 03 ad 5c d7 3d 2a) to time: (40 f3 f4 c1 5a d5 3d 2a)

$ zed lake status -p logs
staged 1tRvK0kTROYpzbDo1UhlpMtu6KD

    Add 1tRvK0tMlG2B0DFJfCMSwwBkhm5 2KiB950B bytes 65 records
       from time: (00 52 5a 1c 89 d7 3d 2a) to time: (60 35 95 90 57 d5 3d 2a)

staged 1tRvKcrC6IaW782uRLhFRvhEdng

    Add 1tRvKfheRh2QcGK2Z4h3ZJd3ZJ2 1KiB138B bytes 21 records
       from time: (d0 6f 03 ad 5c d7 3d 2a) to time: (40 f3 f4 c1 5a d5 3d 2a)
```

But they're definitely no longer _actually_ staged, since if I try to commit them again, I get the appropriate error.

```
$ zed lake commit -p logs 1tRvK0kTROYpzbDo1UhlpMtu6KD 1tRvKcrC6IaW782uRLhFRvhEdng
pool "logs": internal error: serialize transaction: empty transaction
```

### PR DESCRIPTION
**Pull request by mattnibs**
Also have the squash command not exit with error code if staging is
empty (Needed in this pr for the test to work properly).

Closes #2784

### CODE REVIEW

File: api/client/connection.go [hunk 1]
```diff
@@ -33,9 +33,10 @@ var (
 	ErrPoolExists = errors.New("pool exists")
 )
 
-type ReadCloser struct {
+type Response struct {
 	io.ReadCloser
```
Comment (nwt) [inline api/client/connection.go:37]: `Response` is definitely a better name for this! Similar types call their `io.ReadCloser` field `Body`. We might want to do the same.

**Review by nwt — APPROVED** [review]

File: api/client/connection.go (hunk 1 above)
Comment (mattnibs) [reply api/client/connection.go:37]: Ha, yes the ReadCloser name was starting to drive me nuts! Made no sense. Who thought of that name?

Comment (mattnibs) [reply api/client/connection.go:37]: Yeah I can make this Body.
