### PR TITLE
fix dataflow through cut operators

### LINKED ISSUE #2663: fix dataflow bug when cutting layout key
This doesn't seem to do the right thing...
```
zed compile -C -P 2 "from 'pool-ts' | cut x=ts,ts=1"
```
which gives...
```
from (
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x=ts,ts=1;
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x=ts,ts=1;
)
| merge ts
```
The merge here should be on `x`.  I believe this bug was in the original parallelization code so we will put the hazmat PR up and fix this later.

### PR DESCRIPTION
**Pull request by mccanne**
This commit fixes a problem where a query would be incorrectly
parallelized by merging on the wrong key because sufficient
dataflow info was not properly tracked.  While we fixed this
we broke another optimization that doesn't seem important to
maintain (and anyway was based on flawed logic).  These tests
are marked "skip".  When we implement proper dataflow analysis
as part of issue #2756, we can turn the tests back on.

Closes #2663

### CODE REVIEW

File: compiler/optimizer/op.go [hunk 1]
```diff
@@ -140,22 +141,83 @@ func analyzeCuts(assignments []dag.Assignment, layout order.Layout) order.Layout
...
+			for _, d := range dependencies {
+				key := fieldKey(d)
+				if _, ok := scoreboard[key]; ok {
+					// There's a dependency on an ordered
+					// field but we're not sophisticated
+					// enough here to know if this preserves
+					// its order...
+					return order.Nil
+				}
+			}
```
Comment (nwt) [inline compiler/optimizer/op.go:187]: I'm having trouble understanding why this is necessary. It seems like deleting `lhsKey` and continuing on should always be correct (if conservative), regardless of what's inside `a.RHS`. Do you have a motivating example?

File: compiler/optimizer/op.go [hunk 2]
```diff
@@ -140,22 +141,83 @@ func analyzeCuts(assignments []dag.Assignment, layout order.Layout) order.Layout
...
+			// opportunities, e.g., we could do dependency
+			// analysis of a complex RHS expression.
 			return order.Nil
 		}
-		if lhs.Equal(key) {
-			return layout
+		lhsKey := fieldKey(lhs)
+		if rhs == nil {
+			// If the RHS depends on a well-defined set of fields
+			// (non of which are unambiguous like this.foo[this.bar]),
```
Comment (nwt) [inline compiler/optimizer/op.go:169]:
```suggestion
			// (none of which are unambiguous like this.foo[this.bar]),
```

File: compiler/optimizer/op.go [hunk 3]
```diff
@@ -140,22 +141,83 @@ func analyzeCuts(assignments []dag.Assignment, layout order.Layout) order.Layout
...
-		return order.Layout{Keys: field.List{key}, Order: layout.Order}
 	}
-	return order.Nil
+	if len(scoreboard) != 1 {
+		return order.Nil
+	}
+	for _, f := range scoreboard {
+		return order.Layout{Keys: field.List{f}, Order: layout.Order}
+	}
+	panic("unreachable")
```
Comment (nwt) [inline compiler/optimizer/op.go:211]: Not sure this is worth the trouble.
```suggestion
	if len(scoreboard) == 0 {
		return order.Nil
	}
	var maxKey string
	for key := range scoreboard {
		if key > maxKey {
			maxKey = key
		}
	}
	return order.Layout{Keys: field.List{scoreboard[maxkey]}, Order: layout.Order}
```

**Review by nwt — APPROVED** [review]

File: compiler/optimizer/op.go (hunk 1 above)
Comment (mccanne) [reply compiler/optimizer/op.go:187]: It's not conservative to delete something from the scoreboard because to be conservative you need to know there is just one known ordering constraint because the returned layout can only represent one field.  This was essentially the bug in the previous logic.  This will be clarified with the USE-DEF set dataflow analysis when we do this properly.

File: compiler/optimizer/op.go (hunk 3 above)
Comment (mccanne) [reply compiler/optimizer/op.go:211]: This seems more complicated to me.

File: compiler/optimizer/op.go (hunk 1 above)
Comment (nwt) [reply compiler/optimizer/op.go]: > This was essentially the bug in the previous logic.

But the tests pass without this!

File: compiler/optimizer/op.go (hunk 3 above)
Comment (nwt) [reply compiler/optimizer/op.go:211]: I meant that I'm not sure my suggestion is worth the trouble because it's definitely more complicated, but its incorrectness is definitely another strike against it!
