### PR TITLE
user ops: Allow from statements

### LINKED ISSUE #4645: Can't read with "file" from inside User Op
Repro is with Zed commit 90db56f.

The following works ok without User Ops.

```
$ zq -version
Version: v1.8.1-27-g90db56f9

$ cat file_main.zed
file sample.zng | count()

$ zq -I file_main.zed
31(uint64)
```

However, if I try to move the logic to inside a User Op, now it won't get past the CLI tooling.

```
$ cat file_in_op.zed
op CallMe(): (
  file sample.zng | count()
)
CallMe()

$ zq -I file_in_op.zed
no input specified: use a command-line file or a Zed source operator
```

---

Incidentally, while working my way up to that repro, at one point I had this variation with a parameter that caused a panic.

```
$ cat file_in_op_with_param.zed
op CallMe(const param): (
  file sample.zng | count()
)
CallMe("goodbye")

$ echo "null" | zq -I file_in_op_with_param.zed -
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x22a5ca0, 0xc0000ec420})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed/runtime/op.(*exitScope).Pull(0xc0000be078, 0x5?)
	/Users/phil/work/zed/runtime/op/scope.go:46 +0x10e
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc0000be408, 0x80)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0xc0004b8020?, 0x60?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x2b7a8360?, 0x30?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x2b7a8360, 0xc0008222e8}, {0x25c1460, 0xc000120cc0})
	/Users/phil/work/zed/zbuf/batch.go:165 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc000124380, {0xc00003e0b0, 0x1, 0x1})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc0000a8278?, 0x1, 0x1}, {0xc00003e0b0?, 0x1, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc00003e090, 0x3, 0x3})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

It looks like I triggered what may be the same stack dump when attempting the [self `join` example from the tutorial](https://zed.brimdata.io/docs/next/tutorials/join#self-joins).

```
$ zq -version
Version: v1.8.1-28-g23140538

$ cat inner-join-streamed-in-op-with-params.zedop do_join(const left_match, const right_match, ...): (
  switch (
    case has(this[left_match]) => sort flavor
    case has(this[right_match]) => sort likes
  ) | inner join on flavor=likes eater:=name
)
do_join("color", "age", this)

$ cat fruit.ndjson people.ndjson | zq -z -I inner-join-streamed-in-op-with-params.zed -
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/op/catcher.go:25 +0x45
panic({0x22a5be0, 0xc0000c21b0})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/brimdata/zed/runtime/op.(*exitScope).Pull(0xc000932078, 0x5?)
	/Users/phil/work/zed/runtime/op/scope.go:46 +0x10e
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc000932090, 0xc0)
	/Users/phil/work/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0xc0004ba020?, 0x70?)
	/Users/phil/work/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0x2c9d4508?, 0x30?)
	/Users/phil/work/zed/runtime/query.go:91 +0x44
github.com/brimdata/zed/zbuf.CopyPuller({0x2c9d4508, 0xc000932438}, {0x25c1340, 0xc0009b8780})
	/Users/phil/work/zed/zbuf/batch.go:165 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc00002e380, {0xc0000ce040, 0x1, 0x1})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x798
github.com/brimdata/zed/pkg/charm.path.run({0xc0000c4298?, 0x1, 0x1}, {0xc0000ce040?, 0x1, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000061a0?, {0xc0000ce010, 0x4, 0x4})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5d
```

### PR DESCRIPTION
**Pull request by mattnibs**
Closes #4645

### CODE REVIEW

**Comment by philrz** [comment]
@mattnibs: Looks like passing in the pool/filename target is not covered yet. Just curious if you got a sense while you were working on this PR how difficult it might be to add that later? Not sure where its priority will stand among the users, but I've been opening User Ops issues along the way with that aspirational long-term goal of "see if we can get to the point where everything that can be done in the main scope can be done inside a User Op, ideally with parameters".

**Comment by philrz** [comment]
FYI it looks like (modulo parameterized pool/filename refs) #4652 may be mostly covered. For instance, here's the [inner join example](https://zed.brimdata.io/docs/next/tutorials/join#inner-join) from the Join Tutorial implemented inside a User Op with everything else parameterized.

```
$ zq -version
Version: v1.8.1-58-g939f61cd

$ cat inner-join-in-op-params.zed
op CallMe(left_key_field, right_key_field, left_dest, right_source): (
  file fruit.ndjson | sort left_key_field
  | inner join (
    file people.ndjson | sort right_key_field
  ) on left_key_field=right_key_field left_dest:=right_source
)
CallMe(flavor, likes, eater, name)

$ zq -I inner-join-in-op-params.zed
{name:"figs",color:"brown",flavor:"plain",eater:"jessie"}
{name:"banana",color:"yellow",flavor:"sweet",eater:"quinn"}
{name:"strawberry",color:"red",flavor:"sweet",eater:"quinn"}
{name:"dates",color:"brown",flavor:"sweet",note:"in season",eater:"quinn"}
{name:"apple",color:"red",flavor:"tart",eater:"morgan"}
{name:"apple",color:"red",flavor:"tart",eater:"chris"}
```

Though I did bump into this limitation when I try to isolate just the User Op in the imported Zed and make the call from the shell.

```
$ cat inner-join-in-op-params-just-op.zed 
op CallMe(left_key_field, right_key_field, left_dest, right_source): (
  file fruit.ndjson | sort left_key_field
  | inner join (
    file people.ndjson | sort right_key_field
  ) on left_key_field=right_key_field left_dest:=right_source
)

$ zq -I inner-join-in-op-params-just-op.zed 'CallMe(flavor, likes, eater, name)'
redundant inputs specified: use either command-line files or a Zed source operator
```

**Comment by mattnibs** [comment]
> Looks like passing in the pool/filename target is not covered yet.

@philrz separate pr.

File: compiler/semantic/analyzer.go [hunk 1]
```diff
@@ -49,6 +64,37 @@ func (a *analyzer) exitScope() {
...
+				},
+			},
+		}
+		ops, err := a.semPool(pool)
+		if err != nil {
+			return nil, err
+		}
+		return ops[0], nil
+	}
+	return &kernel.Reader{}, nil
```
Comment (nwt) [inline compiler/semantic/analyzer.go:95]: Nit: Indent less.
```suggestion
	if a.head == nil {
		return &kernel.Reader{}, nil
	}
	pool := &ast.Pool{
		Kind: "Pool",
		Spec: ast.PoolSpec{
			Pool: &ast.String{
				Kind: "String",
				Text: "HEAD",
			},
		},
	}
	ops, err := a.semPool(pool)
	if err != nil {
		return nil, err
	}
	return ops[0], nil
```

File: compiler/semantic/analyzer.go [hunk 2]
```diff
@@ -49,6 +64,37 @@ func (a *analyzer) exitScope() {
...
 }
 
+func (a *analyzer) buildFrom(op dag.Op) (dag.Op, error) {
+	switch op := op.(type) {
+	case *kernel.Reader, *dag.Lister, *dag.FileScan, *dag.HTTPScan, *dag.PoolScan, *dag.LakeMetaScan, *dag.PoolMetaScan, *dag.CommitMetaScan, *dag.DeleteScan:
+		return nil, nil
+	case *dag.Scope:
+		return a.buildFrom(op.Body[0])
+	case *dag.Fork:
+		return a.buildFrom(op.Paths[0][0])
```
Comment (nwt) [inline compiler/semantic/analyzer.go:74]: Nit: Alphabetize these so they match the order in compiler/ast/dag/op.go.
```suggestion
	case *dag.Fork:
		return a.buildFrom(op.Paths[0][0])
	case *dag.Scope:
		return a.buildFrom(op.Body[0])
```

File: runtime/op/ztests/user-from.yaml [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+    {a:8}
+
+outputs:
+- name: stdout
+  data: |
+    {a:1}
+    {a:3}
+    {a:5}
+    {a:7}
+    {a:8}
```
Comment (nwt) [inline runtime/op/ztests/user-from.yaml:26]: Use the same indentation style we use in other YAML files.
```suggestion
  - name: test.zed
    data: |
      op fileA(): (
        file A.zson | sort a 
      )
      fileA()
  - name: A.zson
    data: |
      {a:5}
      {a:1}
      {a:7}
      {a:3}
      {a:8}

outputs:
  - name: stdout
    data: |
      {a:1}
      {a:3}
      {a:5}
      {a:7}
      {a:8}
```

File: compiler/job.go [hunk 4]
```diff
@@ -40,14 +40,7 @@ func NewJob(octx *op.Context, in ast.Seq, src *data.Source, head *lakeparse.Comm
...
-		return nil, err
-	}
-	if from != nil {
-		seq.Prepend(from)
-	}
-	entry, err := semantic.Analyze(octx.Context, seq, src, head)
+	entry, reader, err := semantic.Analyze(octx.Context, seq, src, head)
 	if err != nil {
 		return nil, err
 	}
```
Comment (nwt) [inline compiler/job.go:46]: Nit: No need to return a *kernel.Reader from semantic.Analyze since you can just do the same type assertion here.
```suggestion
	entry, err := semantic.Analyze(octx.Context, seq, src, head)
	if err != nil {
		return nil, err
	}
	reader, _ := entry[0].(*kernel.Reader)
```

**Review by nwt — APPROVED** [review]

File: compiler/semantic/analyzer.go [hunk 5]
```diff
@@ -49,6 +62,37 @@ func (a *analyzer) exitScope() {
 	a.scope = a.scope.parent
 }
 
+func (a *analyzer) buildFrom(op dag.Op) (dag.Op, error) {
+	switch op := op.(type) {
+	case *dag.FileScan, *dag.HTTPScan, *dag.PoolScan, *dag.LakeMetaScan, *dag.PoolMetaScan, *dag.CommitMetaScan, *dag.DeleteScan:
+		return nil, nil
+	case *dag.Fork:
+		return a.buildFrom(op.Paths[0][0])
```
Comment (nwt) [inline compiler/semantic/analyzer.go:70]: What's the intuition behind looking at just op.Paths[0] here?
