### PR TITLE
dynamic cut: fix bug in keys

### LINKED ISSUE #4830: cut not producing output equivalent to put+drop
Repro is with Zed commit e03665e.

Start with the successful verification example shown in https://github.com/brimdata/zed/issues/4555#issuecomment-1780316810 that uses attached test data [scan.json.gz](https://github.com/brimdata/zed/files/13183527/scan.json.gz).

```
$ zq -version
Version: v1.10.0-20-ge03665e6

$ zq -Z 'over this | ports:=collect(ports[0]) by ip | put this[ip]:=ports | drop ip,ports' scan.json.gz 
{
    "192.168.5.53": [
        {
            port: 515,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        },
        {
            port: 21,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        }
    ]
}
{
    "192.168.5.49": [
        {
            port: 49152,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        },
        {
            port: 3401,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        }
    ]
}
```

In https://github.com/brimdata/zed/pull/4795#issuecomment-1749695080, @mattnibs pointed out that the `put`/`drop` combo could be improved by replacing it with `cut` as shown below. However, this produces incorrect output: Notice that instead of the separate keys `"192.168.5.49"` and `"192.168.5.53"`, the same key `"192.168.5.53"` appears twice.

```
$ zq -Z 'over this | ports:=collect(ports[0]) by ip | cut this[ip]:=ports' scan.json.gz 
{
    "192.168.5.53": [
        {
            port: 515,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        },
        {
            port: 21,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        }
    ]
}
{
    "192.168.5.53": [
        {
            port: 49152,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        },
        {
            port: 3401,
            proto: "tcp",
            status: "open",
            reason: "syn-ack",
            ttl: 64
        }
    ]
}
```

FWIW, I've noticed that if I run this in a loop sometimes the key `"192.168.5.49"` will show up in both spots instead.

### PR DESCRIPTION
**Pull request by mattnibs**
Fix bug in dynamic cut where two output records with different keys but equal value types would overwrite each other.

Closes #4830

### CODE REVIEW

File: runtime/expr/cutter.go [hunk 1]
```diff
@@ -9,15 +9,13 @@ import (
 )
 
 type Cutter struct {
-	zctx        *zed.Context
-	fieldRefs   field.List
-	fieldExprs  []Evaluator
-	lvals       []*Lval
-	outTypes    *zed.TypeVectorTable
```
Comment (nwt) [inline runtime/expr/cutter.go:16]: I think this can stay here and doesn't need to be in recordBuilderCachedTypes.

Comment (nwt) [reply runtime/expr/cutter.go:16]: (This being `outTypes`.)

Comment (mattnibs) [reply runtime/expr/cutter.go:16]: yep

**Review by nwt — APPROVED** [review]
:shipit:!

**Review by philrz — APPROVED** [review]
Branch tests out well for me too! 👍
