### PR TITLE
unflatten: fix panic on invalid key types

### LINKED ISSUE #3925: unflatten keys as string
This causes a panic...
```
zq 'unflatten([{key:"s",value:1}])'
```
but this is fine...
```
zq 'unflatten([{key:["s"],value:1}])'
```
We shouldn't panic and couls instead return an error but better we should interpret string keys in unflatten as a singleton `[key]`.

### PR DESCRIPTION
**Pull request by mattnibs**
Fix issue where unflatten would panic when encountering an unsupported
key type. Also add support so that key can be a string and return an
error value if an invalid key type is encountered.

Closes #3925

### CODE REVIEW

**Comment by mccanne** [comment]
I noticed this bug now...
```
$ zq 'unflatten([{key:"s",value:1},{key:["s","u"],value:2}])'
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/brimdata/zed/runtime/op.(*Catcher).Pull.func1()
	/Users/mccanne/repo/zed/runtime/op/catcher.go:25 +0x45
panic({0x169ada0, 0x1c7b850})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/brimdata/zed/runtime/expr/function.(*record).addPath(0x0, 0xc00049a718, {0xc00059c130, 0x1, 0x1})
	/Users/mccanne/repo/zed/runtime/expr/function/unflatten.go:135 +0x4b
github.com/brimdata/zed/runtime/expr/function.(*record).addPath(0xc00059a450, 0xc00049a718, {0xc00059c120, 0x2, 0x2})
	/Users/mccanne/repo/zed/runtime/expr/function/unflatten.go:143 +0x36e
github.com/brimdata/zed/runtime/expr/function.(*Unflatten).Call(0xc00049a6e0, {0x2f27b18, 0xc0005ac048}, {0xc00059a090, 0x1, 0xabb10a8?})
	/Users/mccanne/repo/zed/runtime/expr/function/unflatten.go:50 +0x312
github.com/brimdata/zed/runtime/expr.(*Call).Eval(0xc0005a6050, {0xabb10a8?, 0xc0005ac048}, 0x1e5af18?)
	/Users/mccanne/repo/zed/runtime/expr/eval.go:809 +0x84
github.com/brimdata/zed/runtime/op/yield.(*Proc).Pull(0xc00059a0c0, 0x5?)
	/Users/mccanne/repo/zed/runtime/op/yield/yield.go:31 +0x413
github.com/brimdata/zed/runtime/op.(*Single).Pull(0xc0005ac018, 0x20)
	/Users/mccanne/repo/zed/runtime/op/mux.go:134 +0x35
github.com/brimdata/zed/runtime/op.(*Catcher).Pull(0x1?, 0x1?)
	/Users/mccanne/repo/zed/runtime/op/catcher.go:28 +0x6d
github.com/brimdata/zed/runtime.(*Query).Pull(0xabb1028?, 0x48?)
	/Users/mccanne/repo/zed/runtime/query.go:106 +0x45
github.com/brimdata/zed/zbuf.CopyPuller({0xabb1028, 0xc00046eb70}, {0x18e96a0, 0xc00059c060})
	/Users/mccanne/repo/zed/zbuf/batch.go:106 +0x53
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc000225520, {0xc00012e010, 0x1, 0x1})
	/Users/mccanne/repo/zed/cli/zq/command.go:164 +0x74c
github.com/brimdata/zed/pkg/charm.path.run({0xc0001260b0?, 0x1, 0x1}, {0xc00012e010?, 0x1, 0x0?})
	/Users/mccanne/repo/zed/pkg/charm/path.go:11 +0x8b
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0xc0000021a0?, {0xc00012e010, 0x1, 0x1})
	/Users/mccanne/repo/zed/pkg/charm/charm.go:63 +0x4a
main.main()
	/Users/mccanne/repo/zed/cmd/zq/main.go:11 +0x5e
```

**Comment by mattnibs** [comment]
Yeah I didn't account for a user overwriting a set value. I suppose this should just output `{s:{u:2}}`.

What should happen if a user does something like this:

```
unflatten([{key:"a",value:1},{key:"b",value:2},{key:"a",value:"foo"}])
```
?

My instinct is that this should try to create a record `{a:1,b:2,a:"foo"}` which would of course fail when you try to build the type for this.

**Comment by mattnibs** [comment]
@mccanne just pushed a fix for the stack over previous values bug you found.

File: runtime/expr/function/unflatten.go [hunk 1]
```diff
@@ -36,49 +39,67 @@ func (u *Unflatten) Call(ctx zed.Allocator, args []zed.Value) *zed.Value {
...
+		path, typ, vb, err := u.parseElem(array.Type, bytes)
+		if err != nil {
+			return u.zctx.WrapError(err.Error(), ctx.NewValue(array.Type, bytes))
+		}
 		if typ == nil {
 			continue
 		}
-		root.addPath(&u.recordCache, path)
+		removed := root.addPath(&u.recordCache, path)
+		if removed > 0 {
```
Comment (nwt) [inline runtime/expr/function/unflatten.go:51]:
```suggestion
		if removed := root.addPath(&u.recordCache, path); removed > 0 {
```

File: runtime/expr/function/unflatten.go [hunk 2]
```diff
@@ -36,49 +39,67 @@ func (u *Unflatten) Call(ctx zed.Allocator, args []zed.Value) *zed.Value {
...
 	it := vb.Iter()
 	kbytes, vbytes := it.Next(), it.Next()
 	if nkey == 1 {
 		kbytes, vbytes = vbytes, kbytes
 	}
-	return u.decodeKey(kbytes), vtyp, vbytes
+	ktyp := typ.Columns[nkey].Type
+	if ktyp.ID() == zed.IDString {
+		u.path = u.path[:0]
+		u.path = append(u.path, zed.DecodeString(kbytes))
```
Comment (nwt) [inline runtime/expr/function/unflatten.go:96]:
```suggestion
		u.path = append(u.path[:0], zed.DecodeString(kbytes))
```

File: runtime/expr/function/unflatten.go [hunk 3]
```diff
@@ -36,49 +39,67 @@ func (u *Unflatten) Call(ctx zed.Allocator, args []zed.Value) *zed.Value {
...
+		return u.path, vtyp, vbytes, nil
+	}
+	if a, ok := zed.TypeUnder(ktyp).(*zed.TypeArray); ok && a.Type == zed.TypeString {
```
Comment (nwt) [inline runtime/expr/function/unflatten.go:99]: `a.Type` might be a named type.
```suggestion
	if a, ok := zed.TypeUnder(ktyp).(*zed.TypeArray); ok && a.Type.ID() == zed.IDString {
```

File: runtime/expr/function/unflatten.go [hunk 4]
```diff
@@ -114,22 +135,44 @@ type record struct {
...
+		removed = countleaves(r.records[at])
+		if len(p) > 1 {
+			r.records[at] = c.new()
+		} else {
+			r.records[at] = nil
+		}
 	}
-	r.records[len(r.records)-1].addPath(c, p[1:])
+	removed += r.records[len(r.records)-1].addPath(c, p[1:])
+	return removed
```
Comment (nwt) [inline runtime/expr/function/unflatten.go:162]:
```suggestion
	return removed + r.records[len(r.records)-1].addPath(c, p[1:])
```

File: runtime/expr/function/unflatten.go [hunk 5]
```diff
@@ -114,22 +135,44 @@ type record struct {
...
 }
 
-func (r *record) build(zctx *zed.Context, b *zcode.Builder, next func() (zed.Type, zcode.Bytes)) zed.Type {
+func countleaves(rec *record) (count int) {
```
Comment (nwt) [inline runtime/expr/function/unflatten.go:165]: Nits: Make this a method, call it `countLeaves` for consistency with all the other mixedCaps names in this file, and don't use a named result parameter just to save a line.

File: docs/language/functions/unflatten.md [hunk 6]
```diff
@@ -6,7 +6,7 @@ record.
 ### Synopsis
 
 ```
-unflatten(val: [{key:[string],value:any}) -> record
+unflatten(val: [{key:string|[string],value:any}) -> record
```
Comment (nwt) [inline docs/language/functions/unflatten.md:9]: I don't know that we use `|` inside a Zed type like this anywhere else. Maybe use a union?
```suggestion
unflatten(val: [{key:(string,[string]),value:any}) -> record
```

Comment (mattnibs) [reply docs/language/functions/unflatten.md:9]: We do:
https://zed.brimdata.io/docs/language/functions/len/
https://zed.brimdata.io/docs/language/functions/bucket/
https://zed.brimdata.io/docs/language/functions/network_of/

I don't know about union since that to me implies that the value must be a union of type `(string|[string])` though I suppose it could.

Comment (nwt) [reply docs/language/functions/unflatten.md:9]: Those are all top-level lists of types, though. None use `|` inside another complex type.

That said, I don't feel strongly about this, so stick with `|`.

**Review by nwt — APPROVED** [review]
:shipit:!
