### PR TITLE
fix -version flag output for "go install" binaries

### LINKED ISSUE #3777: -version on "go install" binaries shows "unknown"
Now that the Zed GA `v1.0.0` is released, the `go install` command line from the top-level README is working, but running the `-version` option returns `unknown`.

```
$ which zed zq || echo $?
1

$ go install github.com/brimdata/zed/cmd/{zed,zq}@latest

$ which zed zq || echo $?
/Users/phil/.go/bin/zed
/Users/phil/.go/bin/zq

$ zed -version
Version: unknown

$ zq -version
Version: unknown
```

### PR DESCRIPTION
**Pull request by nwt**
The -version flag to zed and zq prints "unknown" for binaries created by
"go install".  Call runtime/debug.ReadBuildInfo and use the reported
main module version instead.

Closes #3777.

### CODE REVIEW

File: cli/cli.go [hunk 1]
```diff
@@ -35,6 +36,14 @@ type Initializer interface {
 
 func (f *Flags) Init(all ...Initializer) (context.Context, context.CancelFunc, error) {
 	if f.showVersion {
+		if Version == "" {
+			Version = "unknown"
+			if info, ok := debug.ReadBuildInfo(); ok {
+				// This will be "(devel)" for binaries not built
+				// by "go install".
```
Comment (mattnibs) [inline cli/cli.go:43]: I got "(devel)" when I did this with go install

Comment (nwt) [reply cli/cli.go]: Fixed in 146feeeaab4f65c64321fa494e0c22d586288ba3.

**Review by mattnibs — APPROVED** [review]
